### ISSUE TITLE
bin/generate is missing

### ISSUE THREAD

**Issue by Yufang-Liu** [chrzyki/candc#2]
Thanks for sharing. 
I try to run the create_data script in candc-2.0/candc/src/scripts/ccg and get the error information "bin/generate is missing". Do you have any idea how to fix it ?

**Comment by chrzyki** [comment]
Heya,

`bin/generate` needs to be compiled (see the [Makefile](https://github.com/chrzyki/candc/blob/1580072da26f5f57ad9d354f934b247b41e4e515/candc/Makefile.targets#L421), `make bin/generate`).

**Comment by Yufang-Liu** [comment]
Solved!!
Thanks a lot. I can't compile v2.0 but v1.0 works.

**Comment by chrzyki** [comment]
Nice. :) I'll have a look whether I can v2.0 to compile and report back.
